In [ ]:
'''
-------------------------------------------------------------
### 0716 오전시험 데이터 전처리 작업계획
-------------------------------------------------------------
1. 데이터 소개. > 세개의 데이터파일을 불러와서 하나의df파일로 합치기.
    - 데이터 크기, 컬럼명, 데이터 타입 확인후에 진행
    - 사용할 함수 (df.shape(), df.info(), df.head())

2. 데이터 전처리
    - 결측치 처리: df.isnull().sunm()
    - 컬럼명 정리.
    - 중복제거.

3. 데이터 분석
    - 서울시 거주/비거주 고객분석
      - 고객 수 : df['주소'].str.contains('서울').value_counts
      - 총 소비액 : df['소비액'].sum()
      - 성비 소비액 : df.groupby('성별')['소비액'].sum()
    - 편의점 소비 분석
      - 전체 편의점 소비액 : df[df['업종']=='편의점']['소비액'].sum()
      - 강남구
    - 지역별 소비 분석
      - 서울시 거주/비거주 소비액: df.groupby('서울시거주여부')['소비액'].sum()
      - 거주지 지역별 편의점 소비액: df[df['업종']=='편의점'].groupby('주소')['소비액'].sum()
'''

In [2]:
import pandas as pd

# 파일경로 지정

file_path = r"../data/bc_card_out2020_03.txt"

# with 문으로 파일 객체를 안전하게 오픈

try :

    with open(file_path, "r", encoding='utf-8') as f:

        df = pd.read_csv(f, sep='\t', low_memory=False)

    print("성공적으로 데이터를 불러왔습니다.")

    print(df.head())

except Exception as e:

    print(f"오류발생: {e}")

# 데이터를 확인해보자

print("데이터 크기 : " , df.shape)

# 결측치 확인해보기

df.info()

성공적으로 데이터를 불러왔습니다.
   REG_YYMM  MEGA_CTY_NO MEGA_CTY_NM  CTY_RGN_NO CTY_RGN_NM  ADMI_CTY_NO  \
0    202003           11       서울특별시        1168        강남구     11680750
1    202003           11       서울특별시        1129        성북구     11290660
2    202003           11       서울특별시        1144        마포구     11440555
3    202003           11       서울특별시        1126        중랑구     11260590
4    202003           11       서울특별시        1168        강남구     11680630

  ADMI_CTY_NM  MAIN_BUZ_CODE MAIN_BUZ_DESC  TP_GRP_NO  ... CSTMR_GUBUN  \
0         수서동           30.0            생활       40.0  ...         내국인
1        길음1동           30.0            생활       70.0  ...         내국인
2         아현동           30.0            생활       40.0  ...         내국인
3        상봉2동           30.0            생활       40.0  ...         내국인
4        대치4동           30.0            생활       62.0  ...         내국인

   CSTMR_MEGA_CTY_NO CSTMR_MEGA_CTY_NM CSTMR_CTY_RGN_NO  CSTMR_CTY_RGN_NM  \
0               11.0             서울특별시           1168.0               강남구
1               11.0             서울특별시           1129.0               성북구
2               11.0             서울특별시           1114.0                중구
3               11.0             서울특별시           1126.0               중랑구
4               41.0               경기도           4146.0               용인시

  SEX_CTGO_CD  AGE_VAL  FLC         AMT     CNT
0         2.0      20대  1.0   7927440.0  1089.0
1         1.0      40대  4.0    274100.0    25.0
2         1.0   60대 이상  5.0  34395725.0   808.0
3         2.0      20대  1.0  31860800.0  3699.0
4         2.0      50대  4.0   2546487.0    45.0

[5 rows x 23 columns]
데이터 크기 :  (878773, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878773 entries, 0 to 878772
Data columns (total 23 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   REG_YYMM           878773 non-null  int64
 1   MEGA_CTY_NO        878773 non-null  int64
 2   MEGA_CTY_NM        878773 non-null  object
 3   CTY_RGN_NO         878773 non-null  int64
 4   CTY_RGN_NM         878773 non-null  object
 5   ADMI_CTY_NO        878773 non-null  int64
 6   ADMI_CTY_NM        878772 non-null  object
 7   MAIN_BUZ_CODE      878772 non-null  float64
 8   MAIN_BUZ_DESC      878772 non-null  object
 9   TP_GRP_NO          878772 non-null  float64
 10  TP_GRP_NM          878772 non-null  object
 11  TP_BUZ_NO          878772 non-null  float64
 12  TP_BUZ_NM          878772 non-null  object
 13  CSTMR_GUBUN        878772 non-null  object
 14  CSTMR_MEGA_CTY_NO  878772 non-null  float64
 15  CSTMR_MEGA_CTY_NM  878772 non-null  object
 16  CSTMR_CTY_RGN_NO   878772 non-null  float64
 17  CSTMR_CTY_RGN_NM   878772 non-null  object
 18  SEX_CTGO_CD        878772 non-null  float64
 19  AGE_VAL            878772 non-null  object
 20  FLC                878772 non-null  float64
 21  AMT                878772 non-null  float64
 22  CNT                878772 non-null  float64
dtypes: float64(9), int64(4), object(10)
memory usage: 154.2+ MB

In [6]:
df.head() #필요한 컬럼 정보 확인.
# 서울시 거주 비거주 인구수 구하기.
# 필요한 컬럼 MEGA_CITY_NO,
# MEGA CITY NUMBER = 11인 AMT의 합과, 나머지의합

,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,TP_GRP_NO,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,202003,11,서울특별시,1168,강남구,11680750,수서동,30.0,생활,40.0,...,내국인,11.0,서울특별시,1168.0,강남구,2.0,20대,1.0,7927440.0,1089.0
1,202003,11,서울특별시,1129,성북구,11290660,길음1동,30.0,생활,70.0,...,내국인,11.0,서울특별시,1129.0,성북구,1.0,40대,4.0,274100.0,25.0
2,202003,11,서울특별시,1144,마포구,11440555,아현동,30.0,생활,40.0,...,내국인,11.0,서울특별시,1114.0,중구,1.0,60대 이상,5.0,34395725.0,808.0
3,202003,11,서울특별시,1126,중랑구,11260590,상봉2동,30.0,생활,40.0,...,내국인,11.0,서울특별시,1126.0,중랑구,2.0,20대,1.0,31860800.0,3699.0
4,202003,11,서울특별시,1168,강남구,11680630,대치4동,30.0,생활,62.0,...,내국인,41.0,경기도,4146.0,용인시,2.0,50대,4.0,2546487.0,45.0

In [7]:
df.isnull().sum() # 결측치 확

REG_YYMM             0
MEGA_CTY_NO          0
MEGA_CTY_NM          0
CTY_RGN_NO           0
CTY_RGN_NM           0
ADMI_CTY_NO          0
ADMI_CTY_NM          1
MAIN_BUZ_CODE        1
MAIN_BUZ_DESC        1
TP_GRP_NO            1
TP_GRP_NM            1
TP_BUZ_NO            1
TP_BUZ_NM            1
CSTMR_GUBUN          1
CSTMR_MEGA_CTY_NO    1
CSTMR_MEGA_CTY_NM    1
CSTMR_CTY_RGN_NO     1
CSTMR_CTY_RGN_NM     1
SEX_CTGO_CD          1
AGE_VAL              1
FLC                  1
AMT                  1
CNT                  1
dtype: int64

In [8]:
df_clean = df.dropna() #결측치가 비교적 적으므로 dropna함수로 삭

In [9]:
# 서울특별시 도시넘버 = 11
df_clean['서울거주여부'] = df_clean['MEGA_CTY_NO'].apply(lambda x: '서울거주' if x == 11 else '비거주')

# 집계 결과 확인
print(df_clean['서울거주여부'].value_counts())

서울거주여부
서울거주    878772
Name: count, dtype: int64

/tmp/ipykernel_780/1389862831.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['서울거주여부'] = df_clean['MEGA_CTY_NO'].apply(lambda x: '서울거주' if x == 11 else '비거주')

In [10]:
#서울시 인구를 컬럼으로 추
df_clean.loc[:, '서울거주여부'] = df_clean['MEGA_CTY_NO'].apply(lambda x: '서울거주' if x == 11 else '비거주')

In [11]:
# 총 소비액 계산
total_amt = df_clean['AMT'].sum()
print("총 소비액:", total_amt)

총 소비액: 1983601655137.0

In [12]:
#성별소비액 구하기. 사용할 컬럼정보는 'sex_ctgo_cd', 'amt'
# 성별 코드 → 라벨 매핑
gender_map = {1: '남성', 2: '여성'}

df_clean['성별'] = df_clean['SEX_CTGO_CD'].map(gender_map)

gender_amt = df_clean.groupby('성별')['AMT'].sum()
print(gender_amt)

성별
남성    1.006046e+12
여성    9.775560e+11
Name: AMT, dtype: float64

/tmp/ipykernel_780/1548323482.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['성별'] = df_clean['SEX_CTGO_CD'].map(gender_map)

In [14]:
#편의점 소비액 구하기, MAIN_BUZ_DESC > 컬럼에 내용들을 확인
# 업종명 고유값 확인
unique_buz = df_clean['MAIN_BUZ_DESC'].unique()
print(unique_buz)

# 업종명 개수 확인
print("업종명 종류 수:", df_clean['MAIN_BUZ_DESC'].nunique())

['생활' '음식' '내구재' '문화' 'T&E' '쇼핑' '유흥' '기타']
업종명 종류 수: 8

In [15]:
#업종명 '생활'로 구분해서 그 합을 구하기
# 업종명이 '생활'인 데이터만 필터링 후 소비액 합계
life_amt = df_clean.loc[df_clean['MAIN_BUZ_DESC'] == '생활', 'AMT'].sum()
print("생활 업종 총 소비액:", life_amt)

생활 업종 총 소비액: 1413357706990.0

In [16]:
#강남구 편의점 소비액 총합 구하기, CSTMR_CTY_RGN_NM > 강남구로 sort
gangnam_df = df_clean.loc[df_clean['CSTMR_CTY_RGN_NM'] == '강남구']
print(gangnam_df.head())  # 강남구 데이터 샘플 확인

     REG_YYMM  MEGA_CTY_NO MEGA_CTY_NM  CTY_RGN_NO CTY_RGN_NM  ADMI_CTY_NO  \
0      202003           11       서울특별시        1168        강남구     11680750
12     202003           11       서울특별시        1156       영등포구     11560540
42     202003           11       서울특별시        1168        강남구     11680640
93     202003           11       서울특별시        1147        양천구     11470590
115    202003           11       서울특별시        1111        종로구     11110650

    ADMI_CTY_NM  MAIN_BUZ_CODE MAIN_BUZ_DESC  TP_GRP_NO  ...  \
0           수서동           30.0            생활       40.0  ...
12          여의동           80.0            음식       80.0  ...
42         역삼1동           30.0            생활       40.0  ...
93         신월4동           30.0            생활       40.0  ...
115         혜화동           30.0            생활       40.0  ...

    CSTMR_MEGA_CTY_NM  CSTMR_CTY_RGN_NO CSTMR_CTY_RGN_NM SEX_CTGO_CD  AGE_VAL  \
0               서울특별시            1168.0              강남구         2.0      20대
12              서울특별시            1168.0              강남구         1.0      50대
42              서울특별시            1168.0              강남구         1.0      30대
93              서울특별시            1168.0              강남구         2.0      30대
115             서울특별시            1168.0              강남구         1.0      20대

     FLC         AMT      CNT  서울거주여부  성별
0    1.0   7927440.0   1089.0    서울거주  여성
12   4.0   5625955.0    445.0    서울거주  남성
42   2.0  70223170.0  10085.0    서울거주  남성
93   2.0     17120.0      4.0    서울거주  여성
115  1.0    188490.0     23.0    서울거주  남성

[5 rows x 25 columns]

In [17]:
#강남구 업종별 집계내역
gangnam_buz_amt = gangnam_df.groupby('MAIN_BUZ_DESC')['AMT'].sum()
print(gangnam_buz_amt)

MAIN_BUZ_DESC
T&E    2.327717e+09
기타     1.340229e+09
내구재    1.452201e+09
문화     2.870588e+09
생활     4.189450e+10
쇼핑     4.279351e+09
유흥     1.307928e+09
음식     8.916747e+09
Name: AMT, dtype: float64

In [19]:
gangnam_convenience_amt = gangnam_df.loc[gangnam_df['MAIN_BUZ_DESC'] == '생활', 'AMT'].sum()
print("강남구 편의점 총 소비액:", gangnam_convenience_amt)

강남구 편의점 총 소비액: 41894502210.0

In [26]:
#서울시 거주 비거주 기준 고객의 소비액 구하기
#서울 거주자 '생활' 소비
seoul_life_amt = df_clean.loc[
    (df_clean['MEGA_CTY_NO'] == 11) & (df_clean['MAIN_BUZ_DESC'] == '생활'),
    'AMT'
].sum()
print("서울거주자의 생활 업종 소비액:", seoul_life_amt)

# 비거주 소비액
non_seoul_life_amt = df_clean.loc[
    (df_clean['MEGA_CTY_NO'] != 11) & (df_clean['MAIN_BUZ_DESC'] == '생활'),
    'AMT'
].sum()
print("비거주자의 생활 업종 소비액:", non_seoul_life_amt)

서울거주자의 생활 업종 소비액: 1413357706990.0
비거주자의 생활 업종 소비액: 0.0

In [21]:
#거주지 소재별 편의점 소비액 구하기
# 거주지 소재별 편의점 소비액 집계
convenience_by_region = df_clean.loc[df_clean['MAIN_BUZ_DESC'] == '생활'] \
    .groupby('CSTMR_CTY_RGN_NM')['AMT'].sum()

print(convenience_by_region)

CSTMR_CTY_RGN_NM
가평군    8.200590e+08
강남구    4.189450e+10
강동구    2.387467e+10
강릉시    3.450042e+09
강북구    1.302326e+10
           ...
홍천군    4.701693e+08
화성시    2.373125e+10
화순군    5.838615e+08
화천군    3.750105e+08
횡성군    4.277495e+08
Name: AMT, Length: 207, dtype: float64